name: Android Kernel CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Enter the kernel version (e.g., v5.14)'
        required: true

jobs:
  check:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: |
          make unit-tests

      - name: Run pycodestyle
        run: |
          make pycodestyle

      - name: Run pylint
        run: |
          make pylint

      - name: Run mypy
        run: |
          make mypy

      - name: Run YAML config validation
        run: |
          make validate-yaml

  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 32  # This is necessary to get the commits

      - name: Get changed files between base and head
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- '*.py' 'kci_*' 'scripts/kci-*' | grep -v '\.md' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Set up Python
        if: env.CHANGED_FILES
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python packages
        if: env.CHANGED_FILES
        run: pip install -r requirements.txt

      - name: Run linting
        if: env.CHANGED_FILES
        run: |
          marian-code/python-lint-annotate@v3 \
          --python-root-list "${{ env.CHANGED_FILES }}" \
          --python-version "3.10" \
          --use-black false \
          --use-flake8 false \
          --use-isort false \
          --use-mypy false \
          --use-pydocstyle false \
          --use-pylint false \
          --use-vulture false

  upload_kernel:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Archive kernel
        uses: actions/upload-artifact@v2
        with:
          name: kernel-zip
          path: |
            # Replace 'build_dir' with the actual directory where your built kernel is located
            zip -r kernel.zip build_dir/*

      - name: Set Kernel Version
        run: echo "KERNEL_VERSION=${{ github.event.inputs.kernel_version }}" >> $GITHUB_ENV

      - name: Tag the Kernel
        run: git tag -a "${{ env.KERNEL_VERSION }}" -m "Release ${{ env.KERNEL_VERSION }}"

      - name: Push Tags
        run: git push origin "${{ env.KERNEL_VERSION }}"
